<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient Form</title>
    <style>
        body {
            font-family: 'Verdana', sans-serif;
            background: url('recep.jpg');
            background-size: cover;
            margin: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        form {
            background-color: rgba(255, 255, 255, 0.8);
            border-radius: 12px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
            padding: 40px;
            text-align: center;
            width: 400px;
        }

        h1 {
            color: #333;
            margin-bottom: 30px;
            font-size: 24px;
        }

        label {
            display: block;
            margin: 15px 0 8px;
            color: #333;
        }

        input,
        select {
            width: 100%;
            padding: 12px;
            margin: 8px 0 20px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 8px;
            font-size: 16px;
        }

        input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 15px 25px;
            font-size: 18px;
            cursor: pointer;
            border-radius: 8px;
            transition: background-color 0.3s ease;
        }

        input[type="submit"]:hover {
            background-color: #0056b3;
        }

        .back-button {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 15px 25px;
            font-size: 18px;
            cursor: pointer;
            border-radius: 8px;
            margin-top: 20px;
            transition: background-color 0.3s ease;
            text-decoration: none;
            display: inline-block;
        }

        .back-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>
    <form action="" method="post">
        <h1>New Patient</h1>
        <label for="patientID">Patient ID:</label>
        <input type="text" id="patientID" name="patientID" value="Autogenerated" readonly>
        <label for="surname">Surname:</label>
        <input type="text" id="surname" name="surname" required>
        <label for="forename">Forename:</label>
        <input type="text" id="forename" name="forename" required>
        <label for="gender">Gender:</label>
        <select id="gender" name="gender" required>
            <option value="male">Male</option>
            <option value="female">Female</option>
            <option value="other">Other</option>
        </select>
        <input type="submit" value="Submit" name="submitPressed">
        <a href="http://localhost/hello/switchboard.php" class="back-button">Back to Switchboard</a>
    </form>

    <?php
    require_once("ConnectToDB.php");

    $servername = "localhost"; // Change to your database server name
    $username = "root"; // Change to your database username
    $password = ""; // Change to your database password
    $dbname = "hospital"; // Change to your database name

    // Create connection
    $conn = new mysqli($servername, $username, $password, $dbname);

    // Check connection
    if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
    }

    if (isset($_POST['submitPressed'])) {
        $surname = $_POST["surname"];
        $forename = $_POST["forename"];
        $gender = $_POST["gender"];

        $SQL = "INSERT INTO hospital.patients (Surname, Forename, Gender) VALUES ('$surname', '$forename', '$gender');";

        if ($conn->query($SQL)) {
            echo "<script>alert('Record written');</script>";
        } else {
            echo "<script>console.log('error xx');</script>";
        }
    }
    ?>
</body>
</html>
